### ISSUE TITLE
Android "Unfortunately, [app_name] has stopped"

### ISSUE THREAD

**Issue by YeeshaYe** [freshplanet/ANE-Facebook#194]
When I am trying to fb login this message appears: "Unfortunately, [app_name] has stopped".
Latest ANE ver. Please help me to solve this problem. Thank you!

My manifest:
                <manifest android:installLocation="auto">
                    <uses-permission android:name="android.permission.INTERNET"/>
                    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
                    <uses-permission android:name="com.android.vending.BILLING" />

```
                <!-- Only this application can receive the messages and registration result -->
                <permission android:name="air.[app_name].permission.C2D_MESSAGE" android:protectionLevel="signature" />
                <uses-permission android:name="air.[app_name].permission.C2D_MESSAGE" />

                <!-- This app has permission to register and receive message -->
                <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

                <application>

                    <activity android:name="com.freshplanet.nativeExtensions.NotificationActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />

                    <receiver android:name="com.freshplanet.nativeExtensions.C2DMBroadcastReceiver"
                    android:permission="com.google.android.c2dm.permission.SEND">

                        <!-- Receive the actual message -->
                        <intent-filter>
                            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                            <category android:name="[app_name]" />
                        </intent-filter>

                        <!-- Receive the registration id -->
                        <intent-filter>
                            <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                            <category android:name="[app_name]" />
                        </intent-filter>
                    </receiver>

                    !-- Local notification -->
                    <service android:name="com.freshplanet.nativeExtensions.LocalNotificationService"/>
                    <receiver android:name="com.freshplanet.nativeExtensions.LocalBroadcastReceiver" android:process=":remote"></receiver>

                    <activity android:name="com.facebook.LoginActivity"/>
                    <activity android:name="com.freshplanet.ane.AirFacebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"></activity>
                    <activity android:name="com.freshplanet.ane.AirFacebook.ShareDialogActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"></activity>
                    <activity android:name="com.freshplanet.ane.AirFacebook.ShareOGActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"></activity>
                    <activity android:name="com.freshplanet.ane.AirFacebook.WebDialogActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"></activity>

                    <activity android:name="com.freshplanet.inapppurchase.activities.BillingActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"></activity>
                </application>
            </manifest>
```

**Comment by YeeshaYe** [comment]
With example from sample folder same thing...any thoughts?

**Comment by phpandroid** [comment]
i also got this message with latest ANE version on Android device. Please fix it help me.

**Comment by vlook** [comment]
Have you checked the system log for the cause of the crash?

I have the exact same issue, and according to the log a missing resource style.Theme_Translucent_NoTitleBar causes the crash. It's already been reported in another issue (https://github.com/freshplanet/ANE-Facebook/issues/175), but I've had no luck with the solution provided there.

E/AndroidRuntime(19815): Caused by: android.content.res.Resources$NotFoundException: style.Theme_Translucent_NoTitleBar
E/AndroidRuntime(19815): 	at com.adobe.air.ResourceIdMap.getId(ResourceIdMap.java:95)
E/AndroidRuntime(19815): 	at com.adobe.fre.FREContext.getResourceId(Native Method)
E/AndroidRuntime(19815): 	at com.freshplanet.ane.AirFacebook.AirFacebookExtension.getResourceId(Unknown Source)
E/AndroidRuntime(19815): 	at com.facebook.widget.WebDialog.<clinit>(Unknown Source)

**Comment by phpandroid** [comment]
Hi vlook, could you tell me how to read the log error?

**Comment by DamboRam** [comment]
Have the same problem , please any solution ?

**Comment by vlook** [comment]
phpandroid, I'm just using logcat to collect the log dumps from the device.

adb logcat -d > androidlog.txt

**Comment by mattmurton** [comment]
If this is the same issue I experienced I've fixed it in my pull request #200  .
A re-built ane binary is included in my latest commit. Let me know if it fixes your problems.

**Comment by mparrett** [comment]
@mattmurton Thanks for your help and info about java 1.6 (that was baffling me!). We just tried your ANE and still have the problem "Unfortunately, [App Name] has stopped." upon trying to call `init()`. Any ideas?

**Comment by jonnyleeharris** [comment]
I was experiencing the same problem upon calling do login with read permissions until I used @mattmurton 's change.

I still get the same error after the login process has completed though.

**Comment by jonnyleeharris** [comment]
E/AndroidRuntime(28585): java.lang.RuntimeException: Unable to pause activity {air.com.rfg.realbingo_prod/com.facebook.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
E/AndroidRuntime(28585): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3225)
E/AndroidRuntime(28585): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3184)
E/AndroidRuntime(28585): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3159)
E/AndroidRuntime(28585): 	at android.app.ActivityThread.access$1000(ActivityThread.java:144)
E/AndroidRuntime(28585): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
E/AndroidRuntime(28585): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(28585): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(28585): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(28585): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28585): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28585): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(28585): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime(28585): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
E/AndroidRuntime(28585): 	at com.facebook.LoginActivity.onPause(Unknown Source)
E/AndroidRuntime(28585): 	at android.app.Activity.performPause(Activity.java:6044)
E/AndroidRuntime(28585): 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1294)
E/AndroidRuntime(28585): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3211)
E/AndroidRuntime(28585): 	... 11 more

**Comment by BadViking** [comment]
I just wanted to chime in and say that we're having the same problem. Has anyone been able to get this working yet? @mattmurton that solution didn't seem to make any difference for me. Same problem after calling openSessionWithReadPermissions, the app crashes with the "Unfortunately, [app_name] has stopped" error.

**Comment by mparrett** [comment]
@BadViking - we reverted back to the working commit 1e6a221 for our Android project due to time constraints.

**Comment by wastedabuser** [comment]
It seems the latest commit contains all of the R.* resource calls and the ANE is built with them. This is causing the problem. The author stated in the README:
>This sdk is using staticaly linked elements. We had to modify all the calls to the com.facebook.android.R package by a custom function that is doing the linking at runtime: import com.freshplanet.ane.AirFacebook.AirFacebookExtension and use AirFacebookExtension.getResourceId("nameOfTheRessource") or AirFacebookExtension.getResourceIds("nameOfTheRessource")
After doing as he said the java.lang.NullPointerException is resolved.

**Comment by hlavko** [comment]
@wastedabuser Is it possible to fork/push your solution with Android ANE please? I think it will help all with the same problem.

**Comment by wastedabuser** [comment]
@hlavko i did, check it out here: https://github.com/wastedabuser/ANE-Facebook

**Comment by CrazyFlasher** [comment]
Same thing...

**Comment by UmberFunk** [comment]
@wastedabuser version works for me, but sadly it's only for Android. 

Minor issues: 
1. Avoid clearing tokens twice. Calling openSessionWithReadPermissions after this crashes app. 
2. Calling openSessionWithReadPermissions, canceling it and calling again causes an "already connected" error.

**Comment by stigmawall** [comment]
I have the exactly same problem like everyone else with the Facebook ANE from freshplanet, change it to the @wastedabuser ANE fixs it.

**Comment by UmberFunk** [comment]
Keep in mind that wastedabuser's ANE works only with Android.

I had struggled a lot with this, found many versions witch supported both platforms and at last made one work, but when I integrated it into our game it failed again. So I switched to commetcial ane and am happy with this decision.

Thanks to Freshplanet for providing opensource extension, but I should let you know that you might lose a lot of time making it work and it can fail anyway.

**Comment by shintiger** [comment]
@wastedabuser Thanks for support! I've heard that the Exception is the SDK problem then I spend whole day for Update freshplanet android source to facebook SDK 4.7, finally I stuck when many error cause java sdk1.6...

Anyway, I simply unpack your ANE and repack it with iOS part (nothing change) , I can use it smoothly either iOS or Android now! 
:+1:
